### ISSUE TITLE
Optimized version

### ISSUE THREAD

**Issue by mpeterv** [kikito/sha1.lua#5]
Hello,

I'm working on a version of this library with some optimizations. Most of the work is done and can be found at https://github.com/mpeterv/sha1.

Optimizations consist of using bit operation libraries on Lua 5.2 and LuaJIT and using native bit operators on Lua 5.3. On Lua 5.1, if no libraries are available, it uses a heavily optimized pure Lua version.

Here are some benchmark results (haven't pushed the benchmarking script yet):

Old:

```
Lua 5.1
                         start up: 0.430182s
sha1 of 512 strings of length 512: 1.342113s

Lua 5.2
                         start up: 0.406454s
sha1 of 512 strings of length 512: 1.398561s

Lua 5.3
                         start up: 0.427973s
sha1 of 512 strings of length 512: 1.704298s

LuaJIT 2.0
                         start up: 0.157024s
sha1 of 512 strings of length 512: 0.069967s
```

New:

```
Lua 5.1 (pure Lua)
                         start up: 0.021682s
sha1 of 512 strings of length 512: 0.594080s

Lua 5.1 (bit module)
                         start up: 0.000390s
sha1 of 512 strings of length 512: 0.126263s

Lua 5.1 (bit32 module)
                         start up: 0.000382s
sha1 of 512 strings of length 512: 0.141718s

Lua 5.2
                         start up: 0.000394s
sha1 of 512 strings of length 512: 0.141130s

Lua 5.3
                         start up: 0.000301s
sha1 of 512 strings of length 512: 0.129986s

LuaJIT 2.0
                         start up: 0.000276s
sha1 of 512 strings of length 512: 0.009888s
```

Most of the code has been rewritten and there are several files now so I'm not sure if `sha1.lua` name fits anymore. The changes could be merged back into this repo but I could also continue development/maintenance in mine (I'd need permissions to publish luarocks releases with the same name though). What do you think?

**Comment by mpeterv** [comment]
Changes applied.

**Comment by tst2005** [comment]
@mpeterv
I see you embedded code about bitwise support.
I still dreams to have a universal-bit module to provide the best bit interface everywhere...
 The optimisation done was made on the bitwise support ? on the sha1 code ? on both ?
* Do you think it is possible to make a stand-alone module with the bitwise code ?
* Maybe this code just cover the sha1 needs only ?

**Comment by mpeterv** [comment]
@tst2005 the code implements some sha1 specific combinations of bitwise operations in pure Lua and using bit/bit32/Lua 53 operators. E.g. it doesn't expose bitwise `and` and `or` and `not` separately but provides a function that calculates `(A and B) or (not A and C)`. This kind of inlining improves performance of the pure Lua version significantly.

Still, it should be easy to modify the code to implement standard `bit32` (or luajit's `bit`) interface, at least for `and`/`or`/`xor`. sha1 does not need shifts but they are relatively easy to add, too

So yes, it should be possible to make a reasonably performant pure Lua polyfill for bitwise operations based on this code.

**Comment by mpeterv** [comment]
For example, adding this to `sha1.pure_lua` module implements bitwise `xor`:

```lua
function ops.bxor(a, b)
   local a1, a2, a3, a4 = uint32_to_bytes(a)
   local b1, b2, b3, b4 = uint32_to_bytes(b)

   return bytes_to_uint32(
      byte_xor_cache[a1 * 256 + b1],
      byte_xor_cache[a2 * 256 + b2],
      byte_xor_cache[a3 * 256 + b3],
      byte_xor_cache[a4 * 256 + b4]
   )
end
```

This doesn't match behaviour of actual `bit32.bxor` precisely - need to accept variable number of arguments and trim them to 32 bits, but it's close.
